[[main]]
  identifier = "about"
  name = "About Me"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "hiking"
  name = "Gallery"
  url = "gallery"
  weight = 3

[[main]]
  parent = "hiking"
  name = "Teufelstättkopf"
  url = "gallery/teufelstaettkopf"

[[main]]
  parent = "hiking"
  name = "Partnachklamm"
  url = "gallery/partnachklamm"

[[main]]
  parent = "hiking"
  name = "Tauern"
  url = "gallery/tauern"

[[main]]
  parent = "hiking"
  name = "Rinnen"
  url = "gallery/rinnen"

[[main]]
  parent = "hiking"
  name = "Krähe"
  url = "gallery/krähe"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 4

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 5

